@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(фермер, "Фермер", "Работа с фермой")
Person(аналитик, "Аналитик", "Работа с BI-системой")
Person(оператор, "Оператор", "Работа с инцидентами")
Person(дежурный, "Дежурный сотрудник", "Работник мониторинга")
Person(дежурный2, "Дежурный сотрудник", "Работник мониторинга")
System(агро, "АгроТех Х - Управление скотом")
System(цифр, "АгроТех Х - Цифровая платформа")


' === Взаимосвязи ===

Rel(директор, цифр, "use")
Rel(аналитик, цифр, "Анализирует")

Rel(фермер, агро, "use")
Rel(оператор, агро, "use")
Rel(дежурный, агро, "use")

Rel(агро, цифр, "")

@enduml