@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(фермер, "Фермер", "Работа с фермой")
Person(аналитик, "Аналитик", "Работа с BI-системой")
Person(оператор, "Оператор", "Работа с инцидентами")
Person(дежурный, "Дежурный сотрудник", "Работник мониторинга")
Person(администратор, "Администратор", "Работа с метриками")

System_Boundary(цифр, "АгроТех Х - Цифровая платформа") {
    System(агро, "АгроТех Х - Управление скотом")
    Container(брокер, "Брокер сообщений")
    Container(аналитика, "Аналитический модуль")
    Container(веб, "Веб-портал")
    Container(BI, "BI-система")

}

' === Взаимосвязи ===

Rel(директор, веб, "use")
Rel(аналитик, BI, "Анализирует")


Rel(брокер, аналитика, "")
Rel(аналитика, веб, "")
Rel(аналитика, BI, "")
Rel(агро, брокер, "")
Rel(администратор, агро, "Изменяет метрики")
Rel(фермер, агро, "use")
Rel(оператор, агро, "use")
Rel(дежурный, агро, "use")

@enduml