@startuml Архитектура_УправлениеСкотом_C4L2_v8

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(фермер, "Фермер", "Работа с фермой")
Person(оператор, "Оператор", "Работа с инцидентами")
Person(дежурный, "Дежурный сотрудник", "Мониторинг")
Person(администратор, "Администратор", "Метрики")

System_Boundary(цифр, "Цифровая платформа") {
    System_Boundary(агро, "АгроТех Х - Управление скотом") {
        Container(дашборд, "UI Дашборд ферм", "React 18", "Мониторинг всех ферм АгроТех")
        
        Container(api, "Сервис бизнес-логики", "", "Управление фермами/алертами")
        Container(фермы, "Сервис ферм", "FastAPI", "Логика ферм")
        Container(service_ai, "Интеграционный слой", "EMQX/NATS", "Маршрутизация видеопотоков от Edge‑агентов")
        Container(yolo, "ИИ Агент", "Local YOLOv26", "Детекция свиней/аномалий")
        ContainerDb(videoDB, "База фреймов для обучения ИИ", "TimescaleDB", "Кадры + метаданные")
        ContainerDb(S3, "База видео", "MinIO")
        ContainerDb(metricsDB, "Metrics DB", "ClickHouse", "Телеметрия ферм")
        Container(алерты, "Сервис уведомлений", "Celery + Redis", "Уведомления")
    }
    Container(keycloak, "Keycloak", "JWT")
    Container(брокер, "Брокер сообщений", "Kafka")
    Container(аналитика, "Аналитический модуль", "ML/Analytics") 
    Container(веб, "Веб-портал", "React/Django")
    Container(BI, "BI-система", "Tableau/PowerBI")
    System_Ext(k8s, "K8S", "Kubernetes")
    System_Ext(prometheus, "Prometheus", "Сбор метрик")
}
Container(grafana, "Grafana", "Dashboard", "Визуализация метрик и алертов")
Container(loki, "Loki", "Logs", "Сбор логов сервисов АгроТех Х")
System_Ext(edge, "Edge-Агенты", "Видео/сенсоры")

Rel(prometheus, grafana, "Метрики")
Rel(metricsDB, grafana, "Телеметрия")
Rel(api, loki, "Логи/трейсы", "HTTP")
Rel(k8s, агро, "Оркестрация на базе k8s")
Rel(брокер, prometheus, "")
Rel(k8s, prometheus, "")
Rel(api, prometheus, "")
Rel(yolo, prometheus, "")
Rel(prometheus, дашборд, "")
Rel(api, keycloak, "Аутенфикация", "gRPC")
Rel(фермер, дашборд, "Мониторинг", "HTTPS")
Rel(оператор, дашборд, "Инциденты", "WebSocket")
Rel(дежурный, дашборд, "Просматривает", "HTTPS")
Rel(дашборд, api, "API", "HTTP/2")
Rel(api, фермы, "Farm data", "gRPC")
Rel(api, yolo, "Inference", "gRPC")
Rel(yolo, videoDB, "Обработанные кадры", "SQL")
Rel(api, S3, "Необработанные видео")
Rel(edge, service_ai, "Видео/MQTT")
Rel(service_ai, api, "")
Rel(алерты, брокер, "События/алерты", "Kafka")
Rel(дашборд, веб, "Единый UI", "iFrame/OAuth")
Rel(metricsDB, BI, "Данные в BI", "JDBC connector")
Rel(аналитика, metricsDB, "Сохраняет агрегированные алерты")
Rel(брокер, аналитика, "Данные")
Rel(аналитика, веб, "Отчеты")
Rel(аналитика, BI, "Метрики")
Rel(администратор, api, "Конфигурация")
Rel(брокер, алерты, "События для алертов")
Rel(брокер, api, "Передача событий алертов")

note right of брокер
ADR-2: Выбор брокера сообщений
Kafka/RabbitMQ
end note

@enduml

